name: ridebookingapp

services:

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    container_name: gateway.api
    build:
      context: .
      dockerfile: src/gateway/Gateway.API/Dockerfile
    depends_on:
      - identityservice
      - dataservice.api
    ports:
      - "63201:8080"
      - "63251:8081"

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    container_name: identityservice
    build:
      context: .
      dockerfile: src/services/IdentityService/Dockerfile
    depends_on:
      - identityservice.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
      - POSTGRES_DB=identitydb
    ports:
      - "63202:8080"
      - "63252:8081"

  identityservice.db:
    image: postgres
    container_name: identityservice.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
      - POSTGRES_DB=identitydb
    volumes:
      - identityservice-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # note: changed port to avoid clash with dataservice.db

  dataservice.api:
    image: ${DOCKER_REGISTRY-}dataserviceapi
    container_name: dataservice.api
    build:
      context: .
      dockerfile: src/services/DataService.API/Dockerfile
    depends_on:
      - dataservice.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
      - POSTGRES_DB=dataservice
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "63203:8080"
      - "63253:8081"

  dataservice.db:
    image: postgres
    container_name: dataservice.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
      - POSTGRES_DB=dataservice
    volumes:
      - dataservice-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    container_name: notificationservice
    build:
      context: .
      dockerfile: src/services/NotificationService/Dockerfile

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8085:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - identityservice.db
      - dataservice.db
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  dataservice-db-data:
  identityservice-db-data:
  pgadmin-data:
  rabbitmq-data:

