services:

  identityservice.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
  
  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: src/services/IdentityService/Dockerfile
    depends_on:
      - identityservice.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "63202:8080"
      - "63252:8081"
 
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/gateway/Gateway.API/Dockerfile
    depends_on:
       - identityservice
    ports:
       - "63201:8080"
       - "63251:8081"
